name: main

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
      - 'tests/*'
      - 'composer.json'
      - '.github/worflows/*'
  schedule:
    - cron:  '20 10 */10 * *'
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: apt install
        shell: bash
        run : |
          sudo apt update 
          sudo apt install plocate
      - name: checkout
        uses: actions/checkout@v4
      - name : composer install
        shell: bash
        run : |
          php -v
          composer install  -q --no-ansi --no-interaction --no-progress
      - name : phpunit
        shell: bash
        run : |
          vendor/bin/phpunit
      - name : log
        shell: bash
        run : |
          date -I > last-tested.txt
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update tested date.
  run-composer-install:
    runs-on: ubuntu-latest
    steps:
      - name: apt install
        shell: bash
        run : |
          sudo apt update 
          sudo apt install plocate
      - name:  installation
        shell: bash
        run: |
          php -v
          composer require takuya/php-plocate-wrapper
          cat <<'EOS' > sample.php
          <?php
          require_once 'vendor/autoload.php';
          use Takuya\PhpPlocateWrapper\LocateWrap;
          use Takuya\PhpPlocateWrapper\LocateDbBuilder;
          $path = realpath(__DIR__);
          $db = sys_get_temp_dir().'/sample.db';
          $builder = new LocateDbBuilder($db, $path,32);
          $locate = new LocateWrap($db);
          $ret = $locate->search('sample');
          var_dump($ret = iterator_to_array($ret));
          EOS
          cat sample.php
          php sample.php
